### ISSUE TITLE
Option to change the name separators for names in Chinese characters

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#28]
If I display the first name of the authors, names in Chinese chacaters would appear as:
`李, 军; 刘, 伟明`
Instead, I would like to be able to display:
`李军；刘伟明`

So, it means two options for names in Chinese characters:
1. Remove the name separator `, `
2. Change the separator between names from `; ` to the Chinese character `；` or `，`.

This is a small thing, but it would be much easier to read in the compact format.

I don't know if this would also apply to Japanese and Korean characters.

**Comment by github-young** [comment]
> If I display the first name of the authors, names in Chinese characters would appear as: `李, 军; 刘, 伟明` Instead, I would like to be able to display: `李军；刘伟明`

If you choose the default option `auto` in name order, the CJK names will be displayed without separators as described by point 1.

If you choose the other two options (First&Last, or Last&First), the separator is designed to be displayed because Chinese people don't express their names in the `First Last` order when they write names in Chinese characters. So a separator here to distinguish the last name is necessary. I don't know about Korean names, but Japanese names should behave the same.

For example: either `刘伟明` or `刘 伟明` is acceptable, but not `伟明刘`, so I display it as `伟明 刘` only for distinguishment.

> 1. Remove the name separator `, `
> 2. Change the separator between names from `; ` to the Chinese character `；` or `，`.

I think 1 is realized in the `auto` option.

For 2, I suggest we keep the English separator between authors, because, in programming practice, Chinese characters are not a good choice for any separation purpose. A case I would consider is that in the future I may develop a function to export the current displayed author list, and all-English-separator is compatible with CSV format and can be more easily handled during post-processing.

> I don't know if this would also apply to Japanese and Korean characters.

I searched Wikipedia for JP and KR names, and I think they should behave the same as Chinese names, that is to have no separator inside names when written in `Last First` order with their native characters; but better to have an explicit separator when written in `First Last` order as it is not a commonly used style.

**Comment by mjthoraval** [comment]
I give below some arguments from a user's perspective. So feel free to tell me if it does not make sense from a coding perspective, or if it would be too complicated to implement.
If you agree on the idea, but feel that you cannot implement it at the moment, I think it would still be useful to keep it as an open issue for other people to eventually pick it and implement it.

> If you choose the default option `auto` in name order, the CJK names will be displayed without separators as described by point 1.

If you choose that option, you are forced to display all the other names as `First Last` order.
This is not what I want. I would like to have `Last First` order for all names.
In my view, the option `Auto (by language`) is not appropriate, as I do not see on what basis it could decide what is better for the user. While it makes sense for CJK languages to have a different convention for writing names, I do not think that you can decide what is the "standard" convention for other names.

Therefore, I would need to have separate settings for CJK languages to achieve what I want.

> Chinese people don't express their names in the `First Last` order when they write names in Chinese characters

Exactly. So there should be 3 separate settings CJK languages: name order, last name - first name separator and separator between names. Making a default choice will probably not be compatible with the diversity of how people will use it.


> For 2, I suggest we keep the English separator between authors, because, in programming practice, Chinese characters are not a good choice for any separation purpose. A case I would consider is that in the future I may develop a function to export the current displayed author list, and all-English-separator is compatible with CSV format and can be more easily handled during post-processing.

I do not really understand this argument. Either:
1. You want to export exactly what is currently displayed in the `Authos List` column. In that case, there is no post-processing to do. You simply export what is already displayed without any processing.
2. Or you want to export to a format that is compatible with CSV format. In that case, you should use the original data in Zotero to format your output, not the data displayed in the  `Authos List` column. I can already decide to put Chinese characters or emojis in the separators fields, and that would already break your all-English-separator assumption.

Applying restrictions based on future developments does not seem justified here.
In the worst case scenario, if you really implement a function that imposes restrictions on the separators you are using, you can simply tell the user that it does not work when the settings are not compatible.

**Comment by github-young** [comment]
I see. You want `Last separator First` style for all (EN/CJK) authors, while the separator for CJK can still be customized (current version doesn't). It is easy to implement.

What is `auto`? It determines if the author names contains CJK. If not, use `First separator Last`, if yes, use `Last separator First`. It is necessary to add a note in the settings.

For the Chinese separator: I hate Chinese separators. But if we implement two different separator settings (one for EN, and another for CJK, that is, to carefully look through the separator processing functions in code), it is OK to fulfil this ask.

Today I cannot make it to contribute more, but another contributor is probably working on the 3 currently open issues, maybe he can help on this as well after I reopen this.

**Comment by mjthoraval** [comment]
Thanks!

**Comment by github-young** [comment]
Closed in [v3.5.1](https://github.com/github-young/zotero-better-authors/releases/tag/v3.5.1)

To be noted that I added an option of setting the separator (within one author's names, _i. e._ `sepIntra`) for CJK characters, but I didn't do so for the separator between authors (_i. e._ `sepInter`) because it is possible that the following authors exist: `` AAA, 刘伟明, BBB``, and since the displayed authors are obtained by a simple `` authorsList.join(sepInter) `` in JS, it is difficult to deal with such cases. 
I will close this issue and in case of any similar requests please file a new issue and refer to this one. Personally, I would not implement this though.

**Comment by mjthoraval** [comment]
Thank you!
